name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu]
    steps:
    - uses: actions/checkout@master
    - name: Rust Release binary
      uses: rust-build/rust-build.action@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Output target
        RUSTTARGET: ${{ matrix.target }}
        # List of extra files to include in build
        EXTRA_FILES: "metacat"
